/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/skp.ts
 * Command: astryx theme build src/themes/skp.ts
 * Generated: 2026-09-07T11:01:11.190Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
