/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/skp.ts
 * Command: astryx theme build src/themes/skp.ts
 * Generated: 2026-09-07T11:01:11.191Z
 */

/// <reference path="./skp.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const skpTheme: DefinedTheme;
