apiVersion: v1
kind: Secret
metadata:
  name: helpudoc-secrets
  namespace: helpudoc
type: Opaque
stringData:
  SESSION_SECRET: replace-me
  POSTGRES_PASSWORD: replace-me
  MINIO_ROOT_USER: replace-me
  MINIO_ROOT_PASSWORD: replace-me
  GEMINI_API_KEY: replace-me
  RAG_LLM_API_KEY: replace-me
